import React, { useState, useEffect } from 'react';
import Layout from '../../../components/Layout';
import Head from 'next/head';
import UserCard from '../../../components/reservations/UserCard';
import BookingModal from '../../../components/Modal/index';
import Link from 'next/link';
import getHeader from '../../../utilis/getHeader';
import API from '../../../utilis/API';
import { useRouter } from 'next/router';
import Loader from '../../../components/Loader';
import { toast } from 'react-toastify';

const index = ({ id }) => {

    const header = getHeader();
    const router = useRouter();
    const [isOpen, setIsOpen] = useState(false)
    const [loading, setloading] = useState(false);
    const [villaInformations, setVillaInformations] = useState();
    const [vendeorInformations, setvendeorInformations] = useState();
    const [imagesShow, setImagesShow] = useState([]);
    const [remainingImgLength, setReminingImgLength] = useState(null);

    // Approve villa
    const approveVilla = () => {
        setloading(true)
        try {
            const { data } = API.get(`Dashboard/approved/villa/${id}`, header);
            console.log(data);
            toast.success('Villa approved successfull')
            setloading(false)
            loaDetailsData();
        } catch (error) {
            setloading(false)
            console.log(error)
        }
    }

    const loaDetailsData = async () => {
        setloading(true)
        try {
            const header = getHeader()
            const { data } = await API.get(`Dashboard/specific/villa/detail/${id}`, header)
            console.log("details", data);

            setVillaInformations(data?.body?.villa_info[0])
            setvendeorInformations(data?.body?.user_info)

            const imgArr = data?.body?.villa_info[0]?.villa_images.slice(0, 5);
            setImagesShow(imgArr)

            const imagesLength = data?.body?.villa_info[0]?.villa_images.length - imgArr?.length;
            setReminingImgLength(imagesLength)

            setloading(false)
        } catch (error) {
            setloading(false)
            console.log(error);
        }
    }

    useEffect(() => {
        loaDetailsData()
    }, [id]);

    return (
        <>
            {loading && <Loader />}
            <Head>
                <title>Villa details</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Layout title="Villa Details">
                <section className='pr-4 pb-7'>
                    <div className='flex justify-between items-center mt-3'>
                        <div>
                            <h1 className='text-[24px] text-black font-sans font-medium'>{`Villa ID ${villaInformations?.id}`}</h1>
                            <p className='text-lightGray text-base py-1 font-sans'>{`Joining Date:${villaInformations?.joining_date}`}</p>
                            <p className='text-lightGray text-base font-sans'>Status <span className={`${villaInformations?.status == "no" ? "text-red-500" : "text-green-500"} font-semibold`}>  {villaInformations?.status == "no" ? "Pending" : "Approved"}</span></p>
                        </div>
                        {villaInformations?.status == "no" && (
                            <button
                                className='w-[176px] h-[46px] bg-success text-white font-light text-sm rounded-[14px]'
                                onClick={approveVilla}
                            >Approve Booking</button>
                        )}
                    </div>
                    <div className='md:flex flex-wrap justify-center md:justify-between mt-10'>
                        <div className=''>
                            <h4 className='text-xl text-darkBlack font-medium'>Villa Information</h4>
                            <div className='mt-5'>
                                <div className='flex mb-3'>
                                    <p className='text-darkGray font-light text-base sm:w-[300px]'>Villa Full Busines name</p>
                                    <p className='text-black text-base'>{villaInformations?.name}</p>
                                </div>
                                <div className='flex mb-3'>
                                    <p className='text-darkGray font-light text-base sm:w-[300px]'>Address</p>
                                    <p className='text-black text-base'>{villaInformations?.address}</p>
                                </div>
                                <div className='flex mb-3'>
                                    <p className='text-darkGray font-light text-base sm:w-[300px]'>City</p>
                                    <p className='text-black text-base'>{villaInformations?.city}</p>
                                </div>
                                <div className='flex mb-3'>
                                    <p className='text-darkGray font-light text-base sm:w-[300px]'>Number of Beds</p>
                                    <p className='text-black text-base'>{villaInformations?.no_of_beds}</p>
                                </div>
                                <div className='flex mb-5'>
                                    <p className='text-darkGray font-light text-base sm:w-[300px]'>Key Features</p>
                                    <p className='text-black text-base'>{villaInformations?.key_features_for_female}<br />{villaInformations?.key_features_for_male}<br /> {villaInformations?.key_features_for_male}<br /></p>
                                </div>
                                <div className='flex mb-3'>
                                    <p className='text-darkGray font-light text-base sm:w-[300px]'>Description</p>
                                    <p className='text-black text-base font-light lg:w-[330px]'>{villaInformations?.description}</p>
                                </div>
                            </div>
                        </div>
                        <div className='w-[333px] rounded-3xl px-6 py-8' style={{ boxShadow: "0px 0px 20px #D7DEE365" }}>
                            <h1 className='text-xl font-medium text-primary'>{"About vendor"}</h1>
                            <div className={`w-full flex flex-col items-center mt-3`}>
                                <h1 className='text-xl font-medium text-darkBlack mt-3'>{vendeorInformations?.name}</h1>
                                <p className='text-xs text-lightGray font-sans font-medium'>{`UserID #${vendeorInformations?.id}`}</p>
                            </div>
                            <div className='my-5'>
                                <div className='flex justify-between items-center my-4'>
                                    <p className='font-light text-lightGray text-sm'>Member Since</p>
                                    <p className='w-[100px] text-darkBlack text-sm'>{vendeorInformations?.date}</p>
                                </div>
                                <div className='flex justify-between items-center my-4'>
                                    <p className='font-light text-lightGray text-sm'>Total villas listed</p>
                                    <p className='w-[100px] text-darkBlack text-sm'>{vendeorInformations?.total_villas}</p>
                                </div>
                                <div className='flex justify-between items-center my-4'>
                                    <p className='font-light text-lightGray text-sm'>Total booking</p>
                                    <p className='w-[100px] text-darkBlack text-sm'>{vendeorInformations?.total_bookings}</p>
                                </div>
                                <div className='flex justify-between items-center my-4'>
                                    <p className='font-light text-lightGray text-sm'>Cancellations</p>
                                    <p className='w-[100px] text-darkBlack text-sm'>{vendeorInformations?.cancelled_bookings}</p>
                                </div>
                            </div>
                            <div className={`text-center mt-8`}>
                                <Link href={`/villa_owners/details/${vendeorInformations?.id}`}>
                                    <button className='w-[150px] h-[42px] text-white text-xs rounded-xl bg-primary'>Go to Profile</button>
                                </Link>
                            </div>
                        </div>
                    </div>
                    <section className=''>
                        <h4 className='text-xl text-darkBlack font-medium'>Villa Images</h4>
                        <div className='flex gap-5 my-5'>
                            {villaInformations?.villa_images?.map((item, index) => (
                                <img src={item?.image} alt='' className='object-cover rounded-xl w-[110px] h-[110px] border border-[#B5D9FF]' />
                            ))}
                            {villaInformations?.villa_images.length > 5 && (
                                <div className='rounded-xl w-[110px] h-[110px] overflow-hidden border-[#B5D9FF] moreImages relative'>
                                    <img src='/img/villa1.jpg' alt='' className='object-cover w-full h-full' />
                                    <span className='text-white font-medium absolute top-[calc(50%-20px)] left-[calc(50%-20px)] translate-x-1/2 translate-y-1/2'>{remainingImgLength}+</span>
                                </div>
                            )}
                        </div>
                        {villaInformations?.status == "no" && (
                            <div className='flex gap-x-10 mt-16'>
                                <button
                                    className='w-[176px] h-[46px] bg-success text-white font-light text-sm rounded-[14px]'
                                    onClick={approveVilla}
                                >Approve Villa</button>
                                <button className='w-[176px] h-[46px] bg-[#AEC4DB] text-white font-light text-sm rounded-[14px]'
                                    onClick={() => router.back()}
                                >Cancel</button>
                            </div>
                        )}
                    </section>
                </section>
            </Layout>
        </>
    )
}

export async function getServerSideProps(context) {
    const { id } = context.query
    return {
        props: {
            id: id
        }
    }
}



export default index